# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56dc41852e7047709d536cf59bbf902b539d57751c9a0cb1a331719d9bfd5a7826a6db5de10b7819d5ca7d529b0a8e21d1c1ef9e8a57e20c93402007c50628d8

test:
  secret_key_base: c3ef2e8d6e164ab286e1df0e88e6e817ea146dd4972b669bb667af1d4fab222198bb4d59e36663d8ecc3922b1221e1b6bd43731f11be480d0994cb2727439b6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
